### ISSUE TITLE
Ecosystem links doesn't work properly

### ISSUE THREAD

**Issue by qanelph** [supervisely-ecosystem/issues#3]
@mkolomeychenko, if you open
https://ecosystem.supervise.ly/collections/collection-action-recognition, you will get
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33942379/180047996-37a7dd88-ab27-467f-acb5-b78bfae7788c.png">

**Comment by mkolomeychenko** [comment]
Thanks, we will check that

**Comment by mkolomeychenko** [comment]
Done!
